name: Typecho Dev Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP only
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Test
      run: |
        find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
  build:
    name: Typecho Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci') && github.event_name != 'pull_request'"
    needs:
        - php
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tree
      run: sudo apt-get -y install tree
    - name: Build
      run: |
        mkdir build
        cp -r LICENSE.txt index.php install.php admin install usr var build/
        mkdir build/usr/uploads/
        chmod 777 build/usr/uploads/
        rm -rf build/admin/src
        cd build && tar -cvf typecho.tar * && mv typecho.tar ../ && cd -
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: typecho
        path: typecho.tar
    - name: Trigger build
      run: |
        curl -XPOST -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/typecho/languages/actions/workflows/update.yml/dispatches --data '{"ref": "master"}'

