name: Typecho Dev Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Typecho Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tree
      run: sudo apt-get -y install tree
    - name: Build
      run: |
        mkdir build
        cp -r LICENSE.txt *.php admin install usr var build/
        mkdir build/usr/uploads/
        chmod 777 build/usr/uploads/
        rm -rf build/admin/src
        tree -d build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: typecho
        path: ./build/
    - name: Trigger build
      run: |
        curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/typecho/languages/actions/workflows/update.yml/dispatches --data '{"ref": "master"}'
